org.srang.madness.region.size: 16
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost:3306/madness}
    username: ${DB_USER:madness}
    password: ${DB_PASS:tourney}
    tomcat.max-active: 50
  messages:
    basename: locale/messages
  thymeleaf.cache: false
  jpa:
    show-sql: true
    properties.hibernate.format_sql: true

hibernate:
  dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  show_sql: true
entitymanager.packages.to.scan: org.srang.madness.manager